export { PostMX } from "./client";
export { verifyWebhookSignature } from "./webhooks";
export type { VerifyWebhookParams } from "./webhooks";
export {
  PostMXError,
  PostMXApiError,
  PostMXNetworkError,
  PostMXWebhookVerificationError,
} from "./errors";
export type {
  PostMXConfig,
  LifecycleMode,
  MessageIntent,
  ContentMode,
  LinkType,
  DeliveryScope,
  InboxMessageAnalysisMode,
  MessageAnalysisStatus,
  CreateInboxParams,
  CreateTemporaryInboxParams,
  ListInboxesParams,
  ListMessagesParams,
  CreateWebhookParams,
  Inbox,
  InboxMessageAnalysis,
  MessageSummary,
  MessageDetail,
  MessageOtpDetail,
  MessageLinksDetail,
  MessageTextOnlyDetail,
  MessageAnalysis,
  ExtractedLink,
  PageInfo,
  WildcardAddress,
  Webhook,
  CreateWebhookResult,
  WaitForMessageOptions,
  WebhookEvent,
  WebhookEventInbox,
} from "./types";
